# Generated by Django 2.0.13 on 2019-03-18 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('baixado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctfidelidade.Clientes')),
            ],
            options={
                'verbose_name_plural': 'premios',
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctfidelidade.Clientes')),
            ],
            options={
                'verbose_name_plural': 'registros',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('validade', models.IntegerField(default=30)),
                ('entradas', models.IntegerField(default=10)),
                ('premio', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'serviços',
            },
        ),
        migrations.AddField(
            model_name='registros',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctfidelidade.Servicos'),
        ),
        migrations.AddField(
            model_name='premios',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctfidelidade.Servicos'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='servicos',
            field=models.ManyToManyField(to='ctfidelidade.Servicos'),
        ),
    ]
