# Generated by Django 2.0.13 on 2019-04-04 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctfidelidade', '0002_clientes_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='servicos',
        ),
        migrations.AlterField(
            model_name='premios',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_ms.Clientes'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_ms.Clientes'),
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
    ]
