# Generated by Django 2.0.13 on 2019-04-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_ms', '0001_initial'),
        ('ctfidelidade', '0003_auto_20190404_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_ms.Empresas')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctfidelidade.Servicos')),
            ],
        ),
    ]
