# Generated by Django 2.0.13 on 2019-04-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctfidelidade', '0003_auto_20190404_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=200)),
                ('servicos', models.ManyToManyField(to='ctfidelidade.Servicos')),
            ],
            options={
                'verbose_name_plural': 'empresas',
            },
        ),
    ]
